#include "/system/learn/attribs.h"
#include "/system/learn/learn.h"
#include "/system/learn/similar.h"
#include <analyse.h>
#include <access.h>
#include <brain.h>
#include <clone.h>
#include <combat.h>
#include <composite.h>
#include <config.h>
#include <description.h>
#include <door.h>
#include <effects.h>
#include <event.h>
#include <filepath.h>
#include <ingredients.h>
#include <language.h>
#include <limits.h>
#include <living.h>
#include <liquid.h>
#include <macros.h>
#include <magic.h>
#include <math.h>
#include <material.h>
#include <money.h>
#include <move.h>
#include <mudtime.h>
#include <net.h>
#include <plant.h>
#include <postscript.h>
#include <properties.h>
#include <race.h>
#include <recipe.h>
#include <room.h>
#include <rr_types.h>
#include <shop.h>
#include <skills.h>
#include <slots.h>
#include <status.h>
#include <state.h>
#include <town.h>
#include <weapon.h>
#include <weather.h>
