/* all events */
# define E_MSG              1
# define E_MOVE             2
# define E_MOVE_INV         3
# define E_ATTACK           4
# define E_ATTACKED_BY      5
# define E_BLOCK            6
# define E_DID_HIT          7
# define E_GOT_HIT          8
# define E_WIELD            9
# define E_WEAR            10
# define E_DEATH           11
# define E_REMOVE_TOOL     12
# define E_MOVE_ATTEMPT    13
# define E_ARRIVED         14
# define E_HEAP_MERGE      15
# define E_CHANGE_ENV      16

# define LISTEN(o) o->query_event(E_MSG)
